### ISSUE TITLE
Offer an example of what `AutoDomainDataWithInMemoryContext` looks like

### ISSUE THREAD

**Issue by atrauzzi** [aivascu/EntityFrameworkCore.AutoFixture#102]
There's one gap in the documentation which is that it doesn't offer an example of what `AutoDomainDataWithInMemoryContext` looks like.

Any chance it can be added?

**Comment by aivascu** [comment]
@atrauzzi indeed the implementation of these attributes might not be obvious to some.
I'll try to add a page on the documentation website to provide some examples.
At the moment you can find these attributes [in the test project](https://github.com/aivascu/EntityFrameworkCore.AutoFixture/tree/master/tests/EntityFrameworkCore.AutoFixture.Tests/Common/Attributes).
