### ISSUE TITLE
NET 5.0 support

### ISSUE THREAD

**Issue by LazyTarget** [aivascu/EntityFrameworkCore.AutoFixture#108]
Would it be possible to upgrade the projects so that .NET 5.0 (and later) is supported?

Maybe like @ccpu has done on his fork?
https://github.com/aivascu/EntityFrameworkCore.AutoFixture/compare/master...ccpu:main

But personally I would still need the support for `netstandard2.0` and `netstandard 2.1`, if possible

Kind regards,
Lazy

**Comment by aivascu** [comment]
Hello @LazyTarget 
I'm a bit confused `net5.0` and `net6.0` are already supported, as well as `netstandard2.0` and 2.1.
Could you update to the latest version and recheck that everything work as expected?
You can check the supported frameworks on [NuGet](https://www.nuget.org/packages/EntityFrameworkCore.AutoFixture/) in the Frameworks tab.

**Comment by LazyTarget** [comment]
Sorry! You are so correct!
