### ISSUE TITLE
No database provider has been configured for this DbContext

### ISSUE THREAD

**Issue by ericgoudriaan** [aivascu/EntityFrameworkCore.AutoFixture#109]
Hi, I'm trying to use the package for unit testing services that get a DbContext injected, but I'm getting the following error:

```
AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance from AutoFixture.Kernel.SeededRequest because creation unexpectedly failed with exception. Please refer to the inner exception to investigate the root cause of the failure.
```

with inner exception: 
```
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

Used this for setup:
```cs
public class InMemoryDataAttribute : AutoDataAttribute
{
    public InMemoryDataAttribute()
        : base(() => new Fixture()
            .Customize(new InMemoryContextCustomization
            {
                OmitDbSets = true,
                AutoCreateDatabase = true
            }))
    {
    }
}

```

And this is an actual test (not testing anything yet though, but it already gives the error before it enters the test):

```cs
[Theory, InMemoryData]
public async Task PlayWithInMemoryData(EmployeeContext employeeContext)
{
    employeeContext.Employees.Add(new Data.Entities.Employee());

    await employeeContext.SaveChangesAsync();
}
```
I thought the InMemoryContextCustomization was intended for the in-memory database provider. Can you help me out here? Thanks in advance.

Best regards,
Eric Goudriaan

**Comment by aivascu** [comment]
Hello @ericgoudriaan 
The error message suggests you don't have a public constructor that accepts the `DbContextOptions<EmployeeContext>` as a parameter. The presence of this constructor is important for the library to be able to inject the database provider into the context.
Could you provide minimum reproducible example or at least the method signatures of your `EmployeeContext` constructors and the `Employee` class so I can investigate the issue?

**Comment by ericgoudriaan** [comment]
Hi @aivascu ,
You're right. Our EmployeeContext has a constructor which takes another IOptions object (which is passed to a ValueGenerator during OnModelCreating), like so:

```
        public EmployeeContext(
            DbContextOptions<EmployeeContext> options,
            IOptions<EmployeePinExpirationOptions> employeePinExpirationOptions) : base(options)
        {
            _employeePinExpirationOptions = employeePinExpirationOptions;
        }

```
It doesn't have a constructor with only the DbContextOptions as a parameter. I added one and commented the part where the other options object is passed to the ValueGenerator just for trying this and it worked. 

But currently we actually need this second options parameter in our constructor. Is there a possibility that this constructor is used?

**Comment by aivascu** [comment]
It should work fine with more than one parameter. Try it out and let me know if it worked for you.

**Comment by yemo1** [comment]
Hi @aivascu,
How possible is it to suppress database transaction warning using this library.
I'm trying to configure DbContextOptions like below.

ConfigureWarnings(x => x.Ignore(InMemoryEventId.TransactionIgnoredWarning) 

I can't see any property to achieve this on the InMemoryContextCustomization

Could you help with this please?

**Comment by aivascu** [comment]
I'm assuming the issue is resolved. Feel free to reopen if you have more questions.

**Comment by ericgoudriaan** [comment]
Sorry I didn't respond anymore... Didn't have much time either and started working on something else... I think the reason why I got this error in the first place is that there was also a parameterless constructor (don't know why that is there though). I can imagine the AutoFixture stuff picks the 'wrong' constructor leaving the options object null...

Anyway, thanks for your fast responses. Issue can stay closed.
