### ISSUE TITLE
SqliteContextCustomization incorret obsolete description

### ISSUE THREAD

**Issue by raphaelm22** [aivascu/EntityFrameworkCore.AutoFixture#121]
The `SqliteContextCustomization`  class has been obsolete and the description suggests using the `InMemoryCustomization`, I think that the correct class is `SqliteCustomization` or not?

**Comment by aivascu** [comment]
@raphaelm22 yes you are correct. The recommended customization for Sqlite is `SqliteCustomization`.
 I'll fix the description in a patch release.
