### ISSUE TITLE
Add support for custom DbContext constructors

### ISSUE THREAD

**Issue by aivascu** [aivascu/EntityFrameworkCore.AutoFixture#24]
Implement support for `DbContext` instance creation using custom constructors.

The custom constructor should contain a `DbContextOptions<T>` parameter and a number of parameters of other types that will be resolved from the current `Fixture`.

**Comment by aivascu** [comment]
@takato1314 the custom constructor issue is fixed. I'll publish a minor version update soon. In the meantime you can use the [preview version](https://www.nuget.org/packages/EntityFrameworkCore.AutoFixture/0.4.4-preview0005) containing the fix.

**Comment by takato1314** [comment]
Hi thx for the fix. I am a bit busy these few days so i will try this out again after this.
